/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.biodata.models.variant.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Clinvar extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Clinvar\",\"namespace\":\"org.opencb.biodata.models.variant.avro\",\"fields\":[{\"name\":\"acc\",\"type\":[\"null\",\"string\"]},{\"name\":\"clinicalSignificance\",\"type\":[\"null\",\"string\"]},{\"name\":\"traits\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"geneName\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"reviewStatus\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.CharSequence acc;
   private java.lang.CharSequence clinicalSignificance;
   private java.util.List<java.lang.CharSequence> traits;
   private java.util.List<java.lang.CharSequence> geneName;
   private java.lang.CharSequence reviewStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Clinvar() {}

  /**
   * All-args constructor.
   */
  public Clinvar(java.lang.CharSequence acc, java.lang.CharSequence clinicalSignificance, java.util.List<java.lang.CharSequence> traits, java.util.List<java.lang.CharSequence> geneName, java.lang.CharSequence reviewStatus) {
    this.acc = acc;
    this.clinicalSignificance = clinicalSignificance;
    this.traits = traits;
    this.geneName = geneName;
    this.reviewStatus = reviewStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return acc;
    case 1: return clinicalSignificance;
    case 2: return traits;
    case 3: return geneName;
    case 4: return reviewStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: acc = (java.lang.CharSequence)value$; break;
    case 1: clinicalSignificance = (java.lang.CharSequence)value$; break;
    case 2: traits = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: geneName = (java.util.List<java.lang.CharSequence>)value$; break;
    case 4: reviewStatus = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'acc' field.
   */
  public java.lang.CharSequence getAcc() {
    return acc;
  }

  /**
   * Sets the value of the 'acc' field.
   * @param value the value to set.
   */
  public void setAcc(java.lang.CharSequence value) {
    this.acc = value;
  }

  /**
   * Gets the value of the 'clinicalSignificance' field.
   */
  public java.lang.CharSequence getClinicalSignificance() {
    return clinicalSignificance;
  }

  /**
   * Sets the value of the 'clinicalSignificance' field.
   * @param value the value to set.
   */
  public void setClinicalSignificance(java.lang.CharSequence value) {
    this.clinicalSignificance = value;
  }

  /**
   * Gets the value of the 'traits' field.
   */
  public java.util.List<java.lang.CharSequence> getTraits() {
    return traits;
  }

  /**
   * Sets the value of the 'traits' field.
   * @param value the value to set.
   */
  public void setTraits(java.util.List<java.lang.CharSequence> value) {
    this.traits = value;
  }

  /**
   * Gets the value of the 'geneName' field.
   */
  public java.util.List<java.lang.CharSequence> getGeneName() {
    return geneName;
  }

  /**
   * Sets the value of the 'geneName' field.
   * @param value the value to set.
   */
  public void setGeneName(java.util.List<java.lang.CharSequence> value) {
    this.geneName = value;
  }

  /**
   * Gets the value of the 'reviewStatus' field.
   */
  public java.lang.CharSequence getReviewStatus() {
    return reviewStatus;
  }

  /**
   * Sets the value of the 'reviewStatus' field.
   * @param value the value to set.
   */
  public void setReviewStatus(java.lang.CharSequence value) {
    this.reviewStatus = value;
  }

  /** Creates a new Clinvar RecordBuilder */
  public static org.opencb.biodata.models.variant.avro.Clinvar.Builder newBuilder() {
    return new org.opencb.biodata.models.variant.avro.Clinvar.Builder();
  }
  
  /** Creates a new Clinvar RecordBuilder by copying an existing Builder */
  public static org.opencb.biodata.models.variant.avro.Clinvar.Builder newBuilder(org.opencb.biodata.models.variant.avro.Clinvar.Builder other) {
    return new org.opencb.biodata.models.variant.avro.Clinvar.Builder(other);
  }
  
  /** Creates a new Clinvar RecordBuilder by copying an existing Clinvar instance */
  public static org.opencb.biodata.models.variant.avro.Clinvar.Builder newBuilder(org.opencb.biodata.models.variant.avro.Clinvar other) {
    return new org.opencb.biodata.models.variant.avro.Clinvar.Builder(other);
  }
  
  /**
   * RecordBuilder for Clinvar instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Clinvar>
    implements org.apache.avro.data.RecordBuilder<Clinvar> {

    private java.lang.CharSequence acc;
    private java.lang.CharSequence clinicalSignificance;
    private java.util.List<java.lang.CharSequence> traits;
    private java.util.List<java.lang.CharSequence> geneName;
    private java.lang.CharSequence reviewStatus;

    /** Creates a new Builder */
    private Builder() {
      super(org.opencb.biodata.models.variant.avro.Clinvar.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.opencb.biodata.models.variant.avro.Clinvar.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.acc)) {
        this.acc = data().deepCopy(fields()[0].schema(), other.acc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clinicalSignificance)) {
        this.clinicalSignificance = data().deepCopy(fields()[1].schema(), other.clinicalSignificance);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.traits)) {
        this.traits = data().deepCopy(fields()[2].schema(), other.traits);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.geneName)) {
        this.geneName = data().deepCopy(fields()[3].schema(), other.geneName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.reviewStatus)) {
        this.reviewStatus = data().deepCopy(fields()[4].schema(), other.reviewStatus);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Clinvar instance */
    private Builder(org.opencb.biodata.models.variant.avro.Clinvar other) {
            super(org.opencb.biodata.models.variant.avro.Clinvar.SCHEMA$);
      if (isValidValue(fields()[0], other.acc)) {
        this.acc = data().deepCopy(fields()[0].schema(), other.acc);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clinicalSignificance)) {
        this.clinicalSignificance = data().deepCopy(fields()[1].schema(), other.clinicalSignificance);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.traits)) {
        this.traits = data().deepCopy(fields()[2].schema(), other.traits);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.geneName)) {
        this.geneName = data().deepCopy(fields()[3].schema(), other.geneName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.reviewStatus)) {
        this.reviewStatus = data().deepCopy(fields()[4].schema(), other.reviewStatus);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'acc' field */
    public java.lang.CharSequence getAcc() {
      return acc;
    }
    
    /** Sets the value of the 'acc' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder setAcc(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.acc = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'acc' field has been set */
    public boolean hasAcc() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'acc' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder clearAcc() {
      acc = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'clinicalSignificance' field */
    public java.lang.CharSequence getClinicalSignificance() {
      return clinicalSignificance;
    }
    
    /** Sets the value of the 'clinicalSignificance' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder setClinicalSignificance(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.clinicalSignificance = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'clinicalSignificance' field has been set */
    public boolean hasClinicalSignificance() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'clinicalSignificance' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder clearClinicalSignificance() {
      clinicalSignificance = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'traits' field */
    public java.util.List<java.lang.CharSequence> getTraits() {
      return traits;
    }
    
    /** Sets the value of the 'traits' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder setTraits(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.traits = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'traits' field has been set */
    public boolean hasTraits() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'traits' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder clearTraits() {
      traits = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'geneName' field */
    public java.util.List<java.lang.CharSequence> getGeneName() {
      return geneName;
    }
    
    /** Sets the value of the 'geneName' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder setGeneName(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.geneName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'geneName' field has been set */
    public boolean hasGeneName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'geneName' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder clearGeneName() {
      geneName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'reviewStatus' field */
    public java.lang.CharSequence getReviewStatus() {
      return reviewStatus;
    }
    
    /** Sets the value of the 'reviewStatus' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder setReviewStatus(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.reviewStatus = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'reviewStatus' field has been set */
    public boolean hasReviewStatus() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'reviewStatus' field */
    public org.opencb.biodata.models.variant.avro.Clinvar.Builder clearReviewStatus() {
      reviewStatus = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Clinvar build() {
      try {
        Clinvar record = new Clinvar();
        record.acc = fieldSetFlags()[0] ? this.acc : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.clinicalSignificance = fieldSetFlags()[1] ? this.clinicalSignificance : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.traits = fieldSetFlags()[2] ? this.traits : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.geneName = fieldSetFlags()[3] ? this.geneName : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[3]);
        record.reviewStatus = fieldSetFlags()[4] ? this.reviewStatus : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
