// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Genome3D.proto

package org.opencb.biodata.models.core.protobuf;

public final class Genome3DModel {
  private Genome3DModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GenomeInteractionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.opencb.biodata.models.core.protobuf.GenomeInteraction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string interactor_a_chr = 1;</code>
     */
    java.lang.String getInteractorAChr();
    /**
     * <code>optional string interactor_a_chr = 1;</code>
     */
    com.google.protobuf.ByteString
        getInteractorAChrBytes();

    /**
     * <code>optional int32 interactor_a_start = 2;</code>
     */
    int getInteractorAStart();

    /**
     * <code>optional int32 interactor_a_end = 3;</code>
     */
    int getInteractorAEnd();

    /**
     * <code>optional string interactor_b_chr = 4;</code>
     */
    java.lang.String getInteractorBChr();
    /**
     * <code>optional string interactor_b_chr = 4;</code>
     */
    com.google.protobuf.ByteString
        getInteractorBChrBytes();

    /**
     * <code>optional int32 interactor_b_start = 5;</code>
     */
    int getInteractorBStart();

    /**
     * <code>optional int32 interactor_b_end = 6;</code>
     */
    int getInteractorBEnd();

    /**
     * <code>repeated string Agene = 7;</code>
     */
    com.google.protobuf.ProtocolStringList
        getAgeneList();
    /**
     * <code>repeated string Agene = 7;</code>
     */
    int getAgeneCount();
    /**
     * <code>repeated string Agene = 7;</code>
     */
    java.lang.String getAgene(int index);
    /**
     * <code>repeated string Agene = 7;</code>
     */
    com.google.protobuf.ByteString
        getAgeneBytes(int index);

    /**
     * <code>repeated string Bgene = 8;</code>
     */
    com.google.protobuf.ProtocolStringList
        getBgeneList();
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    int getBgeneCount();
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    java.lang.String getBgene(int index);
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    com.google.protobuf.ByteString
        getBgeneBytes(int index);

    /**
     * <code>optional string organism = 9;</code>
     */
    java.lang.String getOrganism();
    /**
     * <code>optional string organism = 9;</code>
     */
    com.google.protobuf.ByteString
        getOrganismBytes();

    /**
     * <code>optional string celltissue = 10;</code>
     */
    java.lang.String getCelltissue();
    /**
     * <code>optional string celltissue = 10;</code>
     */
    com.google.protobuf.ByteString
        getCelltissueBytes();

    /**
     * <code>optional string detection_method = 11;</code>
     */
    java.lang.String getDetectionMethod();
    /**
     * <code>optional string detection_method = 11;</code>
     */
    com.google.protobuf.ByteString
        getDetectionMethodBytes();

    /**
     * <code>optional float confidence_score1 = 12;</code>
     */
    float getConfidenceScore1();

    /**
     * <code>optional float confidence_score2 = 13;</code>
     */
    float getConfidenceScore2();

    /**
     * <code>optional int32 contact_frequency = 14;</code>
     */
    int getContactFrequency();

    /**
     * <code>optional int32 pubmed_id = 15;</code>
     */
    int getPubmedId();
  }
  /**
   * Protobuf type {@code org.opencb.biodata.models.core.protobuf.GenomeInteraction}
   */
  public  static final class GenomeInteraction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.opencb.biodata.models.core.protobuf.GenomeInteraction)
      GenomeInteractionOrBuilder {
    // Use GenomeInteraction.newBuilder() to construct.
    private GenomeInteraction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GenomeInteraction() {
      interactorAChr_ = "";
      interactorAStart_ = 0;
      interactorAEnd_ = 0;
      interactorBChr_ = "";
      interactorBStart_ = 0;
      interactorBEnd_ = 0;
      agene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bgene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      organism_ = "";
      celltissue_ = "";
      detectionMethod_ = "";
      confidenceScore1_ = 0F;
      confidenceScore2_ = 0F;
      contactFrequency_ = 0;
      pubmedId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GenomeInteraction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              interactorAChr_ = s;
              break;
            }
            case 16: {

              interactorAStart_ = input.readInt32();
              break;
            }
            case 24: {

              interactorAEnd_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              interactorBChr_ = s;
              break;
            }
            case 40: {

              interactorBStart_ = input.readInt32();
              break;
            }
            case 48: {

              interactorBEnd_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                agene_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              agene_.add(s);
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                bgene_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              bgene_.add(s);
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              organism_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              celltissue_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              detectionMethod_ = s;
              break;
            }
            case 101: {

              confidenceScore1_ = input.readFloat();
              break;
            }
            case 109: {

              confidenceScore2_ = input.readFloat();
              break;
            }
            case 112: {

              contactFrequency_ = input.readInt32();
              break;
            }
            case 120: {

              pubmedId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          agene_ = agene_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          bgene_ = bgene_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencb.biodata.models.core.protobuf.Genome3DModel.internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencb.biodata.models.core.protobuf.Genome3DModel.internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.class, org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.Builder.class);
    }

    private int bitField0_;
    public static final int INTERACTOR_A_CHR_FIELD_NUMBER = 1;
    private volatile java.lang.Object interactorAChr_;
    /**
     * <code>optional string interactor_a_chr = 1;</code>
     */
    public java.lang.String getInteractorAChr() {
      java.lang.Object ref = interactorAChr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interactorAChr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string interactor_a_chr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInteractorAChrBytes() {
      java.lang.Object ref = interactorAChr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interactorAChr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERACTOR_A_START_FIELD_NUMBER = 2;
    private int interactorAStart_;
    /**
     * <code>optional int32 interactor_a_start = 2;</code>
     */
    public int getInteractorAStart() {
      return interactorAStart_;
    }

    public static final int INTERACTOR_A_END_FIELD_NUMBER = 3;
    private int interactorAEnd_;
    /**
     * <code>optional int32 interactor_a_end = 3;</code>
     */
    public int getInteractorAEnd() {
      return interactorAEnd_;
    }

    public static final int INTERACTOR_B_CHR_FIELD_NUMBER = 4;
    private volatile java.lang.Object interactorBChr_;
    /**
     * <code>optional string interactor_b_chr = 4;</code>
     */
    public java.lang.String getInteractorBChr() {
      java.lang.Object ref = interactorBChr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interactorBChr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string interactor_b_chr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInteractorBChrBytes() {
      java.lang.Object ref = interactorBChr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interactorBChr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERACTOR_B_START_FIELD_NUMBER = 5;
    private int interactorBStart_;
    /**
     * <code>optional int32 interactor_b_start = 5;</code>
     */
    public int getInteractorBStart() {
      return interactorBStart_;
    }

    public static final int INTERACTOR_B_END_FIELD_NUMBER = 6;
    private int interactorBEnd_;
    /**
     * <code>optional int32 interactor_b_end = 6;</code>
     */
    public int getInteractorBEnd() {
      return interactorBEnd_;
    }

    public static final int AGENE_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList agene_;
    /**
     * <code>repeated string Agene = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAgeneList() {
      return agene_;
    }
    /**
     * <code>repeated string Agene = 7;</code>
     */
    public int getAgeneCount() {
      return agene_.size();
    }
    /**
     * <code>repeated string Agene = 7;</code>
     */
    public java.lang.String getAgene(int index) {
      return agene_.get(index);
    }
    /**
     * <code>repeated string Agene = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAgeneBytes(int index) {
      return agene_.getByteString(index);
    }

    public static final int BGENE_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList bgene_;
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBgeneList() {
      return bgene_;
    }
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    public int getBgeneCount() {
      return bgene_.size();
    }
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    public java.lang.String getBgene(int index) {
      return bgene_.get(index);
    }
    /**
     * <code>repeated string Bgene = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBgeneBytes(int index) {
      return bgene_.getByteString(index);
    }

    public static final int ORGANISM_FIELD_NUMBER = 9;
    private volatile java.lang.Object organism_;
    /**
     * <code>optional string organism = 9;</code>
     */
    public java.lang.String getOrganism() {
      java.lang.Object ref = organism_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        organism_ = s;
        return s;
      }
    }
    /**
     * <code>optional string organism = 9;</code>
     */
    public com.google.protobuf.ByteString
        getOrganismBytes() {
      java.lang.Object ref = organism_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        organism_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLTISSUE_FIELD_NUMBER = 10;
    private volatile java.lang.Object celltissue_;
    /**
     * <code>optional string celltissue = 10;</code>
     */
    public java.lang.String getCelltissue() {
      java.lang.Object ref = celltissue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        celltissue_ = s;
        return s;
      }
    }
    /**
     * <code>optional string celltissue = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCelltissueBytes() {
      java.lang.Object ref = celltissue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        celltissue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETECTION_METHOD_FIELD_NUMBER = 11;
    private volatile java.lang.Object detectionMethod_;
    /**
     * <code>optional string detection_method = 11;</code>
     */
    public java.lang.String getDetectionMethod() {
      java.lang.Object ref = detectionMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detectionMethod_ = s;
        return s;
      }
    }
    /**
     * <code>optional string detection_method = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDetectionMethodBytes() {
      java.lang.Object ref = detectionMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detectionMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIDENCE_SCORE1_FIELD_NUMBER = 12;
    private float confidenceScore1_;
    /**
     * <code>optional float confidence_score1 = 12;</code>
     */
    public float getConfidenceScore1() {
      return confidenceScore1_;
    }

    public static final int CONFIDENCE_SCORE2_FIELD_NUMBER = 13;
    private float confidenceScore2_;
    /**
     * <code>optional float confidence_score2 = 13;</code>
     */
    public float getConfidenceScore2() {
      return confidenceScore2_;
    }

    public static final int CONTACT_FREQUENCY_FIELD_NUMBER = 14;
    private int contactFrequency_;
    /**
     * <code>optional int32 contact_frequency = 14;</code>
     */
    public int getContactFrequency() {
      return contactFrequency_;
    }

    public static final int PUBMED_ID_FIELD_NUMBER = 15;
    private int pubmedId_;
    /**
     * <code>optional int32 pubmed_id = 15;</code>
     */
    public int getPubmedId() {
      return pubmedId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInteractorAChrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, interactorAChr_);
      }
      if (interactorAStart_ != 0) {
        output.writeInt32(2, interactorAStart_);
      }
      if (interactorAEnd_ != 0) {
        output.writeInt32(3, interactorAEnd_);
      }
      if (!getInteractorBChrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, interactorBChr_);
      }
      if (interactorBStart_ != 0) {
        output.writeInt32(5, interactorBStart_);
      }
      if (interactorBEnd_ != 0) {
        output.writeInt32(6, interactorBEnd_);
      }
      for (int i = 0; i < agene_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, agene_.getRaw(i));
      }
      for (int i = 0; i < bgene_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, bgene_.getRaw(i));
      }
      if (!getOrganismBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, organism_);
      }
      if (!getCelltissueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, celltissue_);
      }
      if (!getDetectionMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, detectionMethod_);
      }
      if (confidenceScore1_ != 0F) {
        output.writeFloat(12, confidenceScore1_);
      }
      if (confidenceScore2_ != 0F) {
        output.writeFloat(13, confidenceScore2_);
      }
      if (contactFrequency_ != 0) {
        output.writeInt32(14, contactFrequency_);
      }
      if (pubmedId_ != 0) {
        output.writeInt32(15, pubmedId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInteractorAChrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, interactorAChr_);
      }
      if (interactorAStart_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, interactorAStart_);
      }
      if (interactorAEnd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, interactorAEnd_);
      }
      if (!getInteractorBChrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, interactorBChr_);
      }
      if (interactorBStart_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, interactorBStart_);
      }
      if (interactorBEnd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, interactorBEnd_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < agene_.size(); i++) {
          dataSize += computeStringSizeNoTag(agene_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAgeneList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < bgene_.size(); i++) {
          dataSize += computeStringSizeNoTag(bgene_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBgeneList().size();
      }
      if (!getOrganismBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, organism_);
      }
      if (!getCelltissueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, celltissue_);
      }
      if (!getDetectionMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, detectionMethod_);
      }
      if (confidenceScore1_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, confidenceScore1_);
      }
      if (confidenceScore2_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(13, confidenceScore2_);
      }
      if (contactFrequency_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, contactFrequency_);
      }
      if (pubmedId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, pubmedId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.opencb.biodata.models.core.protobuf.GenomeInteraction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.opencb.biodata.models.core.protobuf.GenomeInteraction)
        org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteractionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencb.biodata.models.core.protobuf.Genome3DModel.internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencb.biodata.models.core.protobuf.Genome3DModel.internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.class, org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.Builder.class);
      }

      // Construct using org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        interactorAChr_ = "";

        interactorAStart_ = 0;

        interactorAEnd_ = 0;

        interactorBChr_ = "";

        interactorBStart_ = 0;

        interactorBEnd_ = 0;

        agene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        bgene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        organism_ = "";

        celltissue_ = "";

        detectionMethod_ = "";

        confidenceScore1_ = 0F;

        confidenceScore2_ = 0F;

        contactFrequency_ = 0;

        pubmedId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencb.biodata.models.core.protobuf.Genome3DModel.internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor;
      }

      public org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction getDefaultInstanceForType() {
        return org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.getDefaultInstance();
      }

      public org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction build() {
        org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction buildPartial() {
        org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction result = new org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.interactorAChr_ = interactorAChr_;
        result.interactorAStart_ = interactorAStart_;
        result.interactorAEnd_ = interactorAEnd_;
        result.interactorBChr_ = interactorBChr_;
        result.interactorBStart_ = interactorBStart_;
        result.interactorBEnd_ = interactorBEnd_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          agene_ = agene_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.agene_ = agene_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          bgene_ = bgene_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.bgene_ = bgene_;
        result.organism_ = organism_;
        result.celltissue_ = celltissue_;
        result.detectionMethod_ = detectionMethod_;
        result.confidenceScore1_ = confidenceScore1_;
        result.confidenceScore2_ = confidenceScore2_;
        result.contactFrequency_ = contactFrequency_;
        result.pubmedId_ = pubmedId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction) {
          return mergeFrom((org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction other) {
        if (other == org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction.getDefaultInstance()) return this;
        if (!other.getInteractorAChr().isEmpty()) {
          interactorAChr_ = other.interactorAChr_;
          onChanged();
        }
        if (other.getInteractorAStart() != 0) {
          setInteractorAStart(other.getInteractorAStart());
        }
        if (other.getInteractorAEnd() != 0) {
          setInteractorAEnd(other.getInteractorAEnd());
        }
        if (!other.getInteractorBChr().isEmpty()) {
          interactorBChr_ = other.interactorBChr_;
          onChanged();
        }
        if (other.getInteractorBStart() != 0) {
          setInteractorBStart(other.getInteractorBStart());
        }
        if (other.getInteractorBEnd() != 0) {
          setInteractorBEnd(other.getInteractorBEnd());
        }
        if (!other.agene_.isEmpty()) {
          if (agene_.isEmpty()) {
            agene_ = other.agene_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureAgeneIsMutable();
            agene_.addAll(other.agene_);
          }
          onChanged();
        }
        if (!other.bgene_.isEmpty()) {
          if (bgene_.isEmpty()) {
            bgene_ = other.bgene_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureBgeneIsMutable();
            bgene_.addAll(other.bgene_);
          }
          onChanged();
        }
        if (!other.getOrganism().isEmpty()) {
          organism_ = other.organism_;
          onChanged();
        }
        if (!other.getCelltissue().isEmpty()) {
          celltissue_ = other.celltissue_;
          onChanged();
        }
        if (!other.getDetectionMethod().isEmpty()) {
          detectionMethod_ = other.detectionMethod_;
          onChanged();
        }
        if (other.getConfidenceScore1() != 0F) {
          setConfidenceScore1(other.getConfidenceScore1());
        }
        if (other.getConfidenceScore2() != 0F) {
          setConfidenceScore2(other.getConfidenceScore2());
        }
        if (other.getContactFrequency() != 0) {
          setContactFrequency(other.getContactFrequency());
        }
        if (other.getPubmedId() != 0) {
          setPubmedId(other.getPubmedId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object interactorAChr_ = "";
      /**
       * <code>optional string interactor_a_chr = 1;</code>
       */
      public java.lang.String getInteractorAChr() {
        java.lang.Object ref = interactorAChr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interactorAChr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string interactor_a_chr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInteractorAChrBytes() {
        java.lang.Object ref = interactorAChr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interactorAChr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string interactor_a_chr = 1;</code>
       */
      public Builder setInteractorAChr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interactorAChr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string interactor_a_chr = 1;</code>
       */
      public Builder clearInteractorAChr() {
        
        interactorAChr_ = getDefaultInstance().getInteractorAChr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string interactor_a_chr = 1;</code>
       */
      public Builder setInteractorAChrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interactorAChr_ = value;
        onChanged();
        return this;
      }

      private int interactorAStart_ ;
      /**
       * <code>optional int32 interactor_a_start = 2;</code>
       */
      public int getInteractorAStart() {
        return interactorAStart_;
      }
      /**
       * <code>optional int32 interactor_a_start = 2;</code>
       */
      public Builder setInteractorAStart(int value) {
        
        interactorAStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 interactor_a_start = 2;</code>
       */
      public Builder clearInteractorAStart() {
        
        interactorAStart_ = 0;
        onChanged();
        return this;
      }

      private int interactorAEnd_ ;
      /**
       * <code>optional int32 interactor_a_end = 3;</code>
       */
      public int getInteractorAEnd() {
        return interactorAEnd_;
      }
      /**
       * <code>optional int32 interactor_a_end = 3;</code>
       */
      public Builder setInteractorAEnd(int value) {
        
        interactorAEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 interactor_a_end = 3;</code>
       */
      public Builder clearInteractorAEnd() {
        
        interactorAEnd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object interactorBChr_ = "";
      /**
       * <code>optional string interactor_b_chr = 4;</code>
       */
      public java.lang.String getInteractorBChr() {
        java.lang.Object ref = interactorBChr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interactorBChr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string interactor_b_chr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInteractorBChrBytes() {
        java.lang.Object ref = interactorBChr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interactorBChr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string interactor_b_chr = 4;</code>
       */
      public Builder setInteractorBChr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interactorBChr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string interactor_b_chr = 4;</code>
       */
      public Builder clearInteractorBChr() {
        
        interactorBChr_ = getDefaultInstance().getInteractorBChr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string interactor_b_chr = 4;</code>
       */
      public Builder setInteractorBChrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interactorBChr_ = value;
        onChanged();
        return this;
      }

      private int interactorBStart_ ;
      /**
       * <code>optional int32 interactor_b_start = 5;</code>
       */
      public int getInteractorBStart() {
        return interactorBStart_;
      }
      /**
       * <code>optional int32 interactor_b_start = 5;</code>
       */
      public Builder setInteractorBStart(int value) {
        
        interactorBStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 interactor_b_start = 5;</code>
       */
      public Builder clearInteractorBStart() {
        
        interactorBStart_ = 0;
        onChanged();
        return this;
      }

      private int interactorBEnd_ ;
      /**
       * <code>optional int32 interactor_b_end = 6;</code>
       */
      public int getInteractorBEnd() {
        return interactorBEnd_;
      }
      /**
       * <code>optional int32 interactor_b_end = 6;</code>
       */
      public Builder setInteractorBEnd(int value) {
        
        interactorBEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 interactor_b_end = 6;</code>
       */
      public Builder clearInteractorBEnd() {
        
        interactorBEnd_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList agene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAgeneIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          agene_ = new com.google.protobuf.LazyStringArrayList(agene_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAgeneList() {
        return agene_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public int getAgeneCount() {
        return agene_.size();
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public java.lang.String getAgene(int index) {
        return agene_.get(index);
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAgeneBytes(int index) {
        return agene_.getByteString(index);
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public Builder setAgene(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAgeneIsMutable();
        agene_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public Builder addAgene(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAgeneIsMutable();
        agene_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public Builder addAllAgene(
          java.lang.Iterable<java.lang.String> values) {
        ensureAgeneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, agene_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public Builder clearAgene() {
        agene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Agene = 7;</code>
       */
      public Builder addAgeneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAgeneIsMutable();
        agene_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList bgene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBgeneIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          bgene_ = new com.google.protobuf.LazyStringArrayList(bgene_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBgeneList() {
        return bgene_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public int getBgeneCount() {
        return bgene_.size();
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public java.lang.String getBgene(int index) {
        return bgene_.get(index);
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public com.google.protobuf.ByteString
          getBgeneBytes(int index) {
        return bgene_.getByteString(index);
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public Builder setBgene(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBgeneIsMutable();
        bgene_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public Builder addBgene(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBgeneIsMutable();
        bgene_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public Builder addAllBgene(
          java.lang.Iterable<java.lang.String> values) {
        ensureBgeneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bgene_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public Builder clearBgene() {
        bgene_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Bgene = 8;</code>
       */
      public Builder addBgeneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureBgeneIsMutable();
        bgene_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object organism_ = "";
      /**
       * <code>optional string organism = 9;</code>
       */
      public java.lang.String getOrganism() {
        java.lang.Object ref = organism_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          organism_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string organism = 9;</code>
       */
      public com.google.protobuf.ByteString
          getOrganismBytes() {
        java.lang.Object ref = organism_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          organism_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string organism = 9;</code>
       */
      public Builder setOrganism(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        organism_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string organism = 9;</code>
       */
      public Builder clearOrganism() {
        
        organism_ = getDefaultInstance().getOrganism();
        onChanged();
        return this;
      }
      /**
       * <code>optional string organism = 9;</code>
       */
      public Builder setOrganismBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        organism_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object celltissue_ = "";
      /**
       * <code>optional string celltissue = 10;</code>
       */
      public java.lang.String getCelltissue() {
        java.lang.Object ref = celltissue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          celltissue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string celltissue = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCelltissueBytes() {
        java.lang.Object ref = celltissue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          celltissue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string celltissue = 10;</code>
       */
      public Builder setCelltissue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        celltissue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string celltissue = 10;</code>
       */
      public Builder clearCelltissue() {
        
        celltissue_ = getDefaultInstance().getCelltissue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string celltissue = 10;</code>
       */
      public Builder setCelltissueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        celltissue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object detectionMethod_ = "";
      /**
       * <code>optional string detection_method = 11;</code>
       */
      public java.lang.String getDetectionMethod() {
        java.lang.Object ref = detectionMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detectionMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string detection_method = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDetectionMethodBytes() {
        java.lang.Object ref = detectionMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detectionMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string detection_method = 11;</code>
       */
      public Builder setDetectionMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detectionMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string detection_method = 11;</code>
       */
      public Builder clearDetectionMethod() {
        
        detectionMethod_ = getDefaultInstance().getDetectionMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string detection_method = 11;</code>
       */
      public Builder setDetectionMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        detectionMethod_ = value;
        onChanged();
        return this;
      }

      private float confidenceScore1_ ;
      /**
       * <code>optional float confidence_score1 = 12;</code>
       */
      public float getConfidenceScore1() {
        return confidenceScore1_;
      }
      /**
       * <code>optional float confidence_score1 = 12;</code>
       */
      public Builder setConfidenceScore1(float value) {
        
        confidenceScore1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float confidence_score1 = 12;</code>
       */
      public Builder clearConfidenceScore1() {
        
        confidenceScore1_ = 0F;
        onChanged();
        return this;
      }

      private float confidenceScore2_ ;
      /**
       * <code>optional float confidence_score2 = 13;</code>
       */
      public float getConfidenceScore2() {
        return confidenceScore2_;
      }
      /**
       * <code>optional float confidence_score2 = 13;</code>
       */
      public Builder setConfidenceScore2(float value) {
        
        confidenceScore2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float confidence_score2 = 13;</code>
       */
      public Builder clearConfidenceScore2() {
        
        confidenceScore2_ = 0F;
        onChanged();
        return this;
      }

      private int contactFrequency_ ;
      /**
       * <code>optional int32 contact_frequency = 14;</code>
       */
      public int getContactFrequency() {
        return contactFrequency_;
      }
      /**
       * <code>optional int32 contact_frequency = 14;</code>
       */
      public Builder setContactFrequency(int value) {
        
        contactFrequency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 contact_frequency = 14;</code>
       */
      public Builder clearContactFrequency() {
        
        contactFrequency_ = 0;
        onChanged();
        return this;
      }

      private int pubmedId_ ;
      /**
       * <code>optional int32 pubmed_id = 15;</code>
       */
      public int getPubmedId() {
        return pubmedId_;
      }
      /**
       * <code>optional int32 pubmed_id = 15;</code>
       */
      public Builder setPubmedId(int value) {
        
        pubmedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pubmed_id = 15;</code>
       */
      public Builder clearPubmedId() {
        
        pubmedId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.opencb.biodata.models.core.protobuf.GenomeInteraction)
    }

    // @@protoc_insertion_point(class_scope:org.opencb.biodata.models.core.protobuf.GenomeInteraction)
    private static final org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction();
    }

    public static org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenomeInteraction>
        PARSER = new com.google.protobuf.AbstractParser<GenomeInteraction>() {
      public GenomeInteraction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GenomeInteraction(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GenomeInteraction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenomeInteraction> getParserForType() {
      return PARSER;
    }

    public org.opencb.biodata.models.core.protobuf.Genome3DModel.GenomeInteraction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Genome3D.proto\022\'org.opencb.biodata.mod" +
      "els.core.protobuf\"\365\002\n\021GenomeInteraction\022" +
      "\030\n\020interactor_a_chr\030\001 \001(\t\022\032\n\022interactor_" +
      "a_start\030\002 \001(\005\022\030\n\020interactor_a_end\030\003 \001(\005\022" +
      "\030\n\020interactor_b_chr\030\004 \001(\t\022\032\n\022interactor_" +
      "b_start\030\005 \001(\005\022\030\n\020interactor_b_end\030\006 \001(\005\022" +
      "\r\n\005Agene\030\007 \003(\t\022\r\n\005Bgene\030\010 \003(\t\022\020\n\010organis" +
      "m\030\t \001(\t\022\022\n\ncelltissue\030\n \001(\t\022\030\n\020detection" +
      "_method\030\013 \001(\t\022\031\n\021confidence_score1\030\014 \001(\002" +
      "\022\031\n\021confidence_score2\030\r \001(\002\022\031\n\021contact_f",
      "requency\030\016 \001(\005\022\021\n\tpubmed_id\030\017 \001(\005B\017B\rGen" +
      "ome3DModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_opencb_biodata_models_core_protobuf_GenomeInteraction_descriptor,
        new java.lang.String[] { "InteractorAChr", "InteractorAStart", "InteractorAEnd", "InteractorBChr", "InteractorBStart", "InteractorBEnd", "Agene", "Bgene", "Organism", "Celltissue", "DetectionMethod", "ConfidenceScore1", "ConfidenceScore2", "ContactFrequency", "PubmedId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
